@startuml
graph graphname {
  1--2
  1--NULL3[style=invis]
  1--5
  2--3
  2--NULL2[style=invis]
  2--4
  5--NULL1[style=invis]
  5--6
  1[shape=circle, label="1"];
  2[shape=circle, label="2"];
  5[shape=circle, label="5"];
  3[shape=circle, label="3"];
  NULL1[style=invis];
  NULL2[style=invis];
  NULL3[style=invis]
}
@enduml